### ISSUE TITLE
Support for H5101

### ISSUE THREAD

**Issue by jimiamoore** [asednev/homebridge-plugin-govee#10]
This plugin is awesome! My H5072 & H5075 have been rock solid HomeKit devices with this plugin!

Any chance the H5101 could be added? I'd happily purchase you one or do any helpful grunt-work to assist in this effort.

Thanks for all you do!

**Comment by asednev** [comment]
@jimiamoore my research showed that adding support for H5101 (and H5102) should be pretty straightforward. I updated the library that this homebridge plugin is using to read data from the device. I will need your help to test changes with H5101.

Clone  https://github.com/asednev/govee-bt-client/tree/support-h5101

Then, run the following commands and provide console output. 

```
$ npm install
$ npm run dev
```



Here's raw advertisement from my H5075 and decoded on the following lines

```
=== start discovery
discovered 3a1a0e3d40ed4b629616b4adfb824924 3a1a0e3d40ed4b629616b4adfb824924  disconnected -80
3a1a0e3d40ed4b629616b4adfb824924: 88ec0002ef9c4400
{
  uuid: '3a1a0e3d40ed4b629616b4adfb824924',
  address: '',
  model: 'GVH5075_2500',
  battery: 68,
  humidity: 41.2,
  tempInC: 19.2412,
  tempInF: 66.63416,
  rssi: -80
}
````

Your console output will help validate decoding logic. In case decoding is incorrect, few examples of readings will be useful with the values you see on the screen for temperature (C or F) and humidity.

**Comment by KaylaSiemon** [comment]
I would also love this to support H5102.  I believe I successfully cloned the URL above to my homebridge but whenever I run
`npm run dev
`
This is the output I get.  Let me know what I am doing wrong to help assist in this enhancement!  
```
pi@homebridge:/var/lib/homebridge $ npm run dev
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /var/lib/homebridge/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/var/lib/homebridge/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-12-28T20_05_42_584Z-debug.log
pi@homebridge:/var/lib/homebridge $ 
```

**Comment by asednev** [comment]
@KaylaSiemon after cloning the repo, you need to `cd` into the cloned directory:

```
$ cd govee-bt-client
```

followed by

```
$ npm install
$ npm run dev 
```

also, `govee-bt-client` library is unrelated to `homebridge`, it can be cloned anywhere, doesn't have to be inside of homebridge directory.

**Comment by KaylaSiemon** [comment]
discovered a4c1384529b5 a4c1384529b5 a4:c1:38:45:29:b5 disconnected -80
a4c1384529b5: 88ec000309295f00
{
  uuid: 'a4c1384529b5',
  address: 'a4:c1:38:45:29:b5',
  model: 'GVH5072_29B5',
  battery: 95,
  humidity: 95.3,
  tempInC: 19.8953,
  tempInF: 67.81154,
  rssi: -80
}

Is this what you are looking for?

**Comment by KaylaSiemon** [comment]
Opps. I think that's discovering my 5072 model. Let me tryp again

**Comment by KaylaSiemon** [comment]
For some reason, it is unable to get information on my 5102 model i.e. a4:c1:38:e2:8d:16

```
discovered a4c1384529b5 a4c1384529b5 a4:c1:38:45:29:b5 disconnected -78
invalid peripheral, scan for another
discovered a4c138e28d16 a4c138e28d16 a4:c1:38:e2:8d:16 disconnected -75
invalid peripheral, scan for another
discovered a4c1384529b5 a4c1384529b5 a4:c1:38:45:29:b5 disconnected -79
a4c1384529b5: 88ec000305415f00
{
  uuid: 'a4c1384529b5',
  address: 'a4:c1:38:45:29:b5',
  model: 'GVH5072_29B5',
  battery: 95,
  humidity: 95.3,
  tempInC: 19.7953,
  tempInF: 67.63154,
  rssi: -79
}
discovered a4c138e28d16 a4c138e28d16 a4:c1:38:e2:8d:16 disconnected -77
invalid peripheral, scan for another
discovered a4c138e28d16 a4c138e28d16 a4:c1:38:e2:8d:16 disconnected -76
invalid peripheral, scan for another
discovered a4c138e28d16 a4c138e28d16 a4:c1:38:e2:8d:16 disconnected -76
invalid peripheral, scan for another
discovered a4c138e28d16 a4c138e28d16 a4:c1:38:e2:8d:16 disconnected -81
invalid peripheral, scan for another
discovered a4c138e28d16 a4c138e28d16 a4:c1:38:e2:8d:16 disconnected -84
invalid peripheral, scan for another
discovered a4c138e28d16 a4c138e28d16 a4:c1:38:e2:8d:16 disconnected -81
invalid peripheral, scan for another
discovered a4c138e28d16 a4c138e28d16 a4:c1:38:e2:8d:16 disconnected -81
invalid peripheral, scan for another
=== stop discovery
```

**Comment by KaylaSiemon** [comment]
Got it to work! 

Here it is: 
=== start discovery
discovered a4c138e28d16 a4c138e28d16 a4:c1:38:e2:8d:16 disconnected -65
a4c138e28d16: 0100010103165564
{
  uuid: 'a4c138e28d16',
  address: 'a4:c1:38:e2:8d:16',
  model: 'GVH5102_8D16',
  battery: 100,
  humidity: 32.5,
  tempInC: 20.2325,
  tempInF: 68.41850000000001,
  rssi: -65
}

**Comment by KaylaSiemon** [comment]
@asednev Is that what you were looking for?

**Comment by asednev** [comment]
@KaylaSiemon yes! That's great. Thank you for testing. I will update homebridge plugin with support for H5101 in the next week or two.

**Comment by asednev** [comment]
@KaylaSiemon I created version [**1.0.5-beta**](https://www.npmjs.com/package/homebridge-plugin-govee/v/1.0.5) that adds support for H5102. Please update your `homebridge-plugin-govee` to v1.0.5 and give it a try.

Thanks a lot for your help testing this with H5102.

**Comment by KaylaSiemon** [comment]
@asednev It worked! Thank you so much - really appreciate all your hard work!

**Comment by asednev** [comment]
[1.0.5](https://www.npmjs.com/package/homebridge-plugin-govee/v/1.0.5) is now public and available to everyone.
