### ISSUE TITLE
Support for H5074

### ISSUE THREAD

**Issue by CaptBeard** [asednev/homebridge-plugin-govee#11]
**Is your feature request related to a problem? Please describe:**
I have two of the H5074 BLE devices and have been looking for a way to integrate with HomeBridge

**Describe the solution you'd like:**
Support for H5074 model

I can test if you would like.
I have previously looked into doing this on my own (to no avail) but I was able to read the devices from my Pi.

Thanks!

**Comment by asednev** [comment]
@CaptBeard I should be able to add support for H5074 but it may take several weeks due to my limited availability.

If you're willing to try it yourself, I can point you in the right direction. 

`homebridge-plugin-govee` uses `govee-bt-client` to implement the communication with BLE device and decrypt the payload. 

- Here's the PR where I added support for H5101: https://github.com/asednev/govee-bt-client/pull/2/files, take a look at changes to "index.ts".
- You will need to implement identification of H5074 as it's done here: https://github.com/Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci/blob/master/custom_components/govee_ble_hci/govee_advertisement.py#L141
- And decrypt the payload as such: https://github.com/Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci/blob/master/custom_components/govee_ble_hci/govee_advertisement.py#L115

Let me know if that's something that you're up to trying.

**Comment by asednev** [comment]
@CaptBeard It would greatly help if you could capture manufacturerData from your H5074 device. To do that, please clone: 

https://github.com/asednev/govee-bt-client/tree/h5074
then run
```
$ cd govee-bt-client
$ npm install
$ npm run dev
```

look for console outputs. I am interested in the ones that start with `invalid peripheral, manufacturerData=[...]`

there might be multiple similar entries, please provide all variations that you see on console.

**Comment by CaptBeard** [comment]
@asednev 

Not getting anything in the output except:
`=== start discovery`

**Comment by asednev** [comment]
@CaptBeard what system do you run this on and type of operating system? e.g. Mac, PC, RaspberryPi running macOS, Windows, or Linux. And just a sanity check, your system has a bluetooth module in it, right?

Try`$ sudo npm run dev`. that might help with permissions on Linux / macOS.

**Comment by CaptBeard** [comment]
@asednev I'm running it on a Raspberry Pi 3 Model B which I believe has a BCM43438 Wi-Fi/BT module on board.
Tried running it with sudo, no like.
I can try on macOS too

**Comment by asednev** [comment]
@CaptBeard Trying on macOS sounds like a good idea. Other than that, two things come to mind worth trying:

1. Remove UUID filter here: https://github.com/asednev/govee-bt-client/blob/master/src/index.ts#L63
change to
```
await noble.startScanningAsync([], true);
```

2. https://github.com/asednev/govee-bt-client/blob/master/src/index.ts#L6 this line was added to support Raspberry Pi. I know the library works fine for several folks using Raspberry Pi. Maybe there's more to it on your system. I'd recommend checking troubleshooting steps for [noble](https://github.com/abandonware/noble): https://github.com/abandonware/noble#advanced-usage

**Comment by asednev** [comment]
(note to self, here's an example of H5074 payload: https://github.com/wcbonner/GoveeBTTempLogger/blob/master/goveebttemplogger.cpp#L206)

**Comment by CaptBeard** [comment]
I know this may be moot at this point, but I ran it on a fresh Pi4 configuration, here's my output:
`=== start discovery
discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -55
invalid peripheral, manufacturerData=[undefined]
discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -65
invalid peripheral, manufacturerData=[undefined]
discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -81
invalid peripheral, manufacturerData=[88ec008b0436156402]
discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -61
invalid peripheral, manufacturerData=[undefined]
discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -62
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f4857507493e8c2]
discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -79
invalid peripheral, manufacturerData=[88ec008b0436156402]`

**Comment by asednev** [comment]
@CaptBeard  ☝️ is great, thank you for capturing that!

**Comment by asednev** [comment]
@CaptBeard I have an update to the client that should support H5074, would you clone it and give it a try?

https://github.com/asednev/govee-bt-client/tree/h5074
```
$ cd govee-bt-client
$ npm install
$ npm run dev
```

I noticed that your device has mac address starting with `e3:37:3c`, I couldn't find this manufacturer on any of the websites. I added the support for it nonetheless. Do you happen to know if your Pi4 manipulates mac address somehow?

**Comment by CaptBeard** [comment]
Looks like it's pulling the data now:
```
discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -61
e3373cc0d50c: 88ec00ce0397146402
{ uuid: 'e3373cc0d50c',
  address: 'e3:37:3c:c0:d5:0c',
  model: 'Govee_H5074_D50C',
  battery: 100,
  humidity: 52.71,
  tempInC: 9.74,
  tempInF: 49.532,
  rssi: -61 }
```

**Comment by asednev** [comment]
@CaptBeard thank you for verifying. I should have an update to homebridge plugin soon.

**Comment by CaptBeard** [comment]
updated to the latest home bridge plugin. It added one of my sensors (thank you!)
I have another sensor that it doesn't seem to be picking up
here's some debug data, "e3373cc0d50c" is the working sensor:
```

1/29/2021, 11:23:03 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -50
1/29/2021, 11:23:03 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f4857507493e8c2]
1/29/2021, 11:23:03 AM discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -70
1/29/2021, 11:23:03 AM e3373cc0d50c: 88ec00de03a0146402
1/29/2021, 11:23:03 AM discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -70
1/29/2021, 11:23:03 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740cd5c2]
1/29/2021, 11:23:05 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -68
1/29/2021, 11:23:05 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f4857507493e8c2]
1/29/2021, 11:23:05 AM discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -65
1/29/2021, 11:23:05 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740cd5c2]
1/29/2021, 11:23:05 AM discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -66
1/29/2021, 11:23:05 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740cd5c2]
1/29/2021, 11:23:06 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -67
1/29/2021, 11:23:06 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f4857507493e8c2]
1/29/2021, 11:23:06 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -67
1/29/2021, 11:23:06 AM invalid peripheral, manufacturerData=[88ec007d07c01b6402]
1/29/2021, 11:23:07 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -65
1/29/2021, 11:23:07 AM invalid peripheral, manufacturerData=[88ec007d07c01b6402]
1/29/2021, 11:23:07 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -66
1/29/2021, 11:23:07 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f4857507493e8c2]
1/29/2021, 11:23:08 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -52
1/29/2021, 11:23:08 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f4857507493e8c2]
1/29/2021, 11:23:08 AM discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -65
1/29/2021, 11:23:08 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740cd5c2]
1/29/2021, 11:23:08 AM discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -67
1/29/2021, 11:23:08 AM e3373cc0d50c: 88ec00db03a0146402
1/29/2021, 11:23:09 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -48
1/29/2021, 11:23:09 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f4857507493e8c2]
1/29/2021, 11:23:09 AM discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -71
1/29/2021, 11:23:09 AM e3373cc0d50c: 88ec00db03a0146402
1/29/2021, 11:23:09 AM discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -71
1/29/2021, 11:23:09 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740cd5c2]
1/29/2021, 11:23:11 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -68
1/29/2021, 11:23:11 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f4857507493e8c2]
1/29/2021, 11:23:11 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -69
1/29/2021, 11:23:11 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f4857507493e8c2]
1/29/2021, 11:23:11 AM discovered e3373cc0d50c e3373cc0d50c e3:37:3c:c0:d5:0c disconnected -55
1/29/2021, 11:23:11 AM invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740cd5c2]
```

**Comment by rkanar** [comment]
I get the same "invalid peripheral" error for all 3 of my H5074 units in 1.0.7.

Here are some Bluetooth scan results of my units, in the event there's anything helpful to you here:

```
[CHG] Device E3:5E:CC:92:D8:D5 RSSI: -77
[CHG] Device E3:5E:CC:B1:C0:CC RSSI: -73
[CHG] Device E3:5E:CC:72:40:E8 RSSI: -60
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  00 7c 02 76 19 64 02                             .|.v.d.
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 e8 40 c2                             HWPt.@.
[CHG] Device E3:5E:CC:92:D8:D5 RSSI: -59
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Value:
  00 cc 07 e6 0a 64 02                             .....d.
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 d5 d8 c2                             HWPt...
[CHG] Device E3:5E:CC:B1:C0:CC RSSI: -76
[CHG] Device E3:5E:CC:72:40:E8 RSSI: -61
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  00 7a 02 75 19 64 02                             .z.u.d.
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 e8 40 c2                             HWPt.@.
[CHG] Device E3:5E:CC:72:40:E8 RSSI: -58
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  00 77 02 74 19 64 02                             .w.t.d.
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 e8 40 c2                             HWPt.@.
[CHG] Device E3:5E:CC:92:D8:D5 RSSI: -61
[CHG] Device E3:5E:CC:B1:C0:CC RSSI: -72
[DEL] Device E3:5E:CC:92:D8:D5 Govee_H5074_D8D5
[DEL] Device E3:5E:CC:B1:C0:CC Govee_H5074_C0CC
[DEL] Device E3:5E:CC:72:40:E8 Govee_H5074_40E8
[NEW] Device E3:5E:CC:B1:C0:CC Govee_H5074_C0CC
[CHG] Device E3:5E:CC:B1:C0:CC RSSI: -74
[CHG] Device E3:5E:CC:B1:C0:CC ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:B1:C0:CC ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 cc c0 c2                             HWPt...
[NEW] Device E3:5E:CC:72:40:E8 Govee_H5074_40E8
[NEW] Device E3:5E:CC:92:D8:D5 Govee_H5074_D8D5
[CHG] Device E3:5E:CC:72:40:E8 RSSI: -61
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  00 7c 02 73 19 64 02                             .|.s.d.
[CHG] Device E3:5E:CC:92:D8:D5 RSSI: -62
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Value:
  00 cb 07 e7 0a 64 02                             .....d.
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 d5 d8 c2                             HWPt...
[CHG] Device E3:5E:CC:B1:C0:CC RSSI: -75
[CHG] Device E3:5E:CC:B1:C0:CC ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:B1:C0:CC ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 cc c0 c2                             HWPt...
[CHG] Device E3:5E:CC:B1:C0:CC ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:B1:C0:CC ManufacturerData Value:
  00 ec 01 d8 13 64 02                             .....d.
[CHG] Device E3:5E:CC:B1:C0:CC RSSI: -76
[CHG] Device E3:5E:CC:B1:C0:CC ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:B1:C0:CC ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 cc c0 c2                             HWPt...
[CHG] Device E3:5E:CC:B1:C0:CC ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:B1:C0:CC ManufacturerData Value:
  00 ee 01 d8 13 64 02                             .....d.
[CHG] Device E3:5E:CC:72:40:E8 RSSI: -70
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  00 7c 02 73 19 64 02                             .|.s.d.
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 e8 40 c2                             HWPt.@.
[CHG] Device E3:5E:CC:92:D8:D5 RSSI: -59
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Value:
  00 ca 07 ea 0a 64 02                             .....d.
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 d5 d8 c2                             HWPt...
[CHG] Device E3:5E:CC:B1:C0:CC RSSI: -75
[CHG] Device E3:5E:CC:92:D8:D5 RSSI: -61
[CHG] Device E3:5E:CC:72:40:E8 RSSI: -62
[CHG] Device E3:5E:CC:B1:C0:CC RSSI: -75
[CHG] Device E3:5E:CC:92:D8:D5 RSSI: -59
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Value:
  00 c9 07 e8 0a 64 02                             .....d.
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:92:D8:D5 ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 d5 d8 c2                             HWPt...
[CHG] Device E3:5E:CC:B1:C0:CC RSSI: -74
[CHG] Device E3:5E:CC:72:40:E8 RSSI: -64
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  00 7d 02 73 19 64 02                             .}.s.d.
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 e8 40 c2                             HWPt.@.
[CHG] Device E3:5E:CC:B1:C0:CC RSSI: -74
[CHG] Device E3:5E:CC:72:40:E8 RSSI: -68
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0xec88
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  00 7c 02 73 19 64 02                             .|.s.d.
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Key: 0x004c
[CHG] Device E3:5E:CC:72:40:E8 ManufacturerData Value:
  02 15 49 4e 54 45 4c 4c 49 5f 52 4f 43 4b 53 5f  ..INTELLI_ROCKS_
  48 57 50 74 e8 40 c2                             HWPt.@.
```

**Comment by asednev** [comment]
```
1/29/2021, 11:23:07 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -65
1/29/2021, 11:23:07 AM invalid peripheral, manufacturerData=[88ec007d07c01b6402]
```
This payload looks like something that would be decoded. The resound it's marked invalid is the MAC address. `e0:12:1d` doesn't match known pattern for Govee devices. 

I will make MAC address filter optional and expose configuration to turn that off. You are the first person affected by that. I suspect there is something about your system that's different. A configuration parameter will help to work around that limitation.

**Comment by CaptBeard** [comment]
I have a lot of BLE devices in my home, which could be causing that, but here are my two H5074 devices, where only 1 is working:
e3:37:3c:c0:d5:0c (Govee_H5074_D50C) <- device detected and added to Home
e0:12:1d:60:e8:93 (Govee_H5074_E893) <- not added to Home

**Comment by doggkruse** [comment]
@asednev I'm not seeing the need to filter by known mac addresses at all.  Do you have some background on why this is required?  Noble is already filtering for devices that advertise the Govee services [ec88, 0001] so the mac filter should be unnecessary.

I suspect the [0001] service is not unique and it was added to handle other devices that may advertise that service.  The most robust solution here may be to only use the mac filtering for devices not using the [ec88] service uuid.

**Comment by brandonpamplin** [comment]
> ```
> 1/29/2021, 11:23:07 AM discovered e0121d60e893 e0121d60e893 e0:12:1d:60:e8:93 disconnected -65
> 1/29/2021, 11:23:07 AM invalid peripheral, manufacturerData=[88ec007d07c01b6402]
> ```
> 
> 
> This payload looks like something that would be decoded. The reason it's marked invalid is the MAC address. `e0:12:1d` doesn't match known pattern for Govee devices.
> 
> 
> I will make MAC address filter optional and expose configuration to turn that off. You are the first person affected by that. I suspect there is something about your system that's different. A configuration parameter will help to work around that limitation.

I'm also experiencing the same problem with what appears to be MAC filtering for my HS5074. Not being that guy on the internet trying to be like "FIX MY FREE PLUGIN THAT YOU'RE DEVELOPING ON YOUR OWN TIME!"...just letting you know that there are others that fall in the same boat. Thanks for your time and efforts in helping out the community.

Debug mode shows:

```
discovered e0121cc18cb8 e0121cc18cb8 e0:12:1c:c1:8c:b8 disconnected -78
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f48575074b88cc2]
discovered e0121cc18cb8 e0121cc18cb8 e0:12:1c:c1:8c:b8 disconnected -73
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f48575074b88cc2]
discovered e0121cc18cb8 e0121cc18cb8 e0:12:1c:c1:8c:b8 disconnected -74
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f48575074b88cc2]
discovered e0121cc18cb8 e0121cc18cb8 e0:12:1c:c1:8c:b8 disconnected -72
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f48575074b88cc2]
discovered e0121cc18cb8 e0121cc18cb8 e0:12:1c:c1:8c:b8 disconnected -74
```

**Comment by asednev** [comment]
@brandonpamplin awesome, thanks for sharing. I will iterate on this feedback and make the plugin more usable.

Worth mentioning that `manufacturerData=[4c000215494e54454c4c495f524f434b535f48575074b88cc2]` isn't valid payload. If your output has something starting with `88ec`, once MAC address filter is lifted it will start working for you.

**Comment by asednev** [comment]
I pushed an update to npm that removes MAC filter. Try to install [v1.0.8](https://www.npmjs.com/package/homebridge-plugin-govee/v/1.0.8).

**Comment by brandonpamplin** [comment]
> I pushed an update to npm that removes MAC filter. Try to install [v1.0.8](https://www.npmjs.com/package/homebridge-plugin-govee/v/1.0.8).

Awesome. Just updated and it is working now! Thanks again!
