### ISSUE TITLE
Adjust (calibrate) humidity reading?

### ISSUE THREAD

**Issue by anthonyb82** [asednev/homebridge-plugin-govee#13]
My hygrometer has always run about 10% high. Is there something I could add to the config to reduce the value displayed in homekit by the device? I’m running the h5072.

**Comment by asednev** [comment]
@anthonyb82 Did you try to check Govee app for calibration settings? My H5075 can be calibrated in the device settings.

**Comment by anthonyb82** [comment]
I appreciate the response! Yes. It is calibrated through the app and it shows properly there and on the device. For some reason, the result pulling in to homekit is the raw result (without the calibration adjustment).

**Comment by asednev** [comment]
@anthonyb82 Looks like Govee broadcasts raw readings. I added a setting for humidity offset in [1.0.6](https://www.npmjs.com/package/homebridge-plugin-govee/v/1.0.6) (you'll have to install it as beta), please give it a try and let me know if that does the job.

**Comment by anthonyb82** [comment]
This works perfectly! Thank you so very much for taking your time to make the adjustment for me. Matched it to the offset I have in govee and all looks great now. My cigars thank you as well 😊
