### ISSUE TITLE
Plugin name is confusing

### ISSUE THREAD

**Issue by apexad** [asednev/homebridge-plugin-govee#2]
Just something else I wanted to mention, the name of this plugin considering it's unique purpose is too simple.  It could easily be confused with the Govee Light plugin (which uses the Govee API, not bluetooth) https://www.npmjs.com/package/homebridge-govee

Perhaps renaming it to `homebridge-govee-thermo-hygrometer` or something?

**Comment by asednev** [comment]
Thanks for pointing out, I will consider renaming.

**Comment by asednev** [comment]
@apexad I did my research, looks like changing name of npm package isn't possible. Technically I'd have to deprecate plugin with this name and create a new plugin with a different name. I'll keep current name for now and will consider options.

https://docs.npmjs.com/unpublishing-packages-from-the-registry

**Comment by apexad** [comment]
Take a look at https://stackoverflow.com/questions/28371669/renaming-a-published-npm-module as this provides a decent way to do it.

Otherwise the package.json changes you made in https://github.com/asednev/homebridge-plugin-govee/commit/0daf490b6539d77c338c58eb0a231b50b60c5e70#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 will help a lot.
