### ISSUE TITLE
Identifying/Creating duplicate devices with strange characters

### ISSUE THREAD

**Issue by steveredden** [asednev/homebridge-plugin-govee#25]
**Describe The Bug:**

The plugin appears to be finding the same device but with extra non-printable-characters in various places:

![image](https://user-images.githubusercontent.com/35814432/111040777-6127e800-83fa-11eb-90d0-7bdffa21e201.png)

I have tried deleting these extraneous/duplicate devices from the cache but they keep coming back

Perhaps needs some ascii encoding of device name prior to accepting? Some kind of bluetooth issue that we need to account for?

**To Reproduce:**

Auto-discovery

**Expected behavior:**

The real device:
![image](https://user-images.githubusercontent.com/35814432/111040802-8b79a580-83fa-11eb-84fb-b3f57c7629d6.png)

Its duplicate with a strange name:
![image](https://user-images.githubusercontent.com/35814432/111040824-a4825680-83fa-11eb-9281-e9c2aaadce3e.png)

**Logs:**

```
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: GVH5075BCCA
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: GVH5075F5C1
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: GVH5075E486
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: GVH50753CCC
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: GVH5075E46
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: GVH5075F51
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: VH50753CCC
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: VH5075F5C1
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: GVH50753CC
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: GVH5075FC1
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: GVH5075E86
[13/03/2021, 12:46:06] [Govee] Loading accessory from cache: GVH5075BCA
```

**Plugin Config:**

```json
{
            "name": "Govee",
            "batteryThreshold": 15,
            "debug": false,
            "humidityOffset": 0,
            "platform": "GoveeHomebridgePlugin"
}
```

**Environment:**

* **Plugin Version**: v1.0.8
* **Homebridge Version**: v1.3.3
* **Node.js Version**: v14.15.4
* **NPM Version**: v6.14.11
* **Operating System**: Raspbian

**Comment by asednev** [comment]
@steveredden thank you for reporting this issue. I've seen several instances of the same. I think there is something that I can do to limit allowed characters, please stand by for an update.

**Comment by asednev** [comment]
@steveredden I created a new beta version [1.1.1](https://www.npmjs.com/package/homebridge-plugin-govee/v/1.1.1). Please give it a try and let me know if the fix worked for you.

**Comment by steveredden** [comment]
I've upgraded.  I assume the validation will just be "wait a few days and hope no new devices appear"?

**Comment by asednev** [comment]
> I've upgraded. I assume the validation will just be "wait a few days and hope no new devices appear"?

Sounds about right 🤠

**Comment by radeonx1800** [comment]
Homebridge on Pi 3b, everything updated, duplicate instance of one specific H5075 appeared for me too. 
I’ve removed/reinstalled the plugin, upgraded to the beta plugin today, issue persists. Will monitor and see if anything changes. Other than these phantom readings this plugin works fantastic!

**Comment by asednev** [comment]
> Homebridge on Pi 3b, everything updated, duplicate instance of one specific H5075 appeared for me too.
> I’ve removed/reinstalled the plugin, upgraded to the beta plugin today, issue persists. Will monitor and see if anything changes. Other than these phantom readings this plugin works fantastic!

Just to clarify, new version won't remove accessories with wrong names that were added previously. You can remove those manually by selecting "Remove Single Cached Accessory" in the homebridge settings.

**Comment by steveredden** [comment]
I think there's still an issue. I continue to get items.

Perhaps a supplemental change is to verify string length / pattern matching?

Seems you may have eliminated the weird boxes, but are all H5075 devices named as follows:

regex:  GVH5075[A-Z0-9]{4}

If it doesn't match maybe we can exclude it as a discovered device?

**Comment by steveredden** [comment]
`^GVH\d{4}[A-F0-0]{4}$` may be more accurate, and universal for other device types?
