### ISSUE TITLE
Raspberry Pi + Homebridge + Bluetooth?

### ISSUE THREAD

**Issue by cargueta001** [asednev/homebridge-plugin-govee#3]
Hello @asednev 
I was curious, does this plugin support Raspberry Pi with Homebridge? I dug into the Linux details and saw it had Raspbian support but I wanted to clarify since I didn’t see the RPI3+ as a supported device.
If it is supported, could you provide any details as to how I could get it installed?

Thanks for the clarification!

**Comment by asednev** [comment]
You can take a look at https://github.com/asednev/homebridge-plugin-govee/issues/1. I am yet to get to updating the dependency to support different format of MAC addresses.

**Comment by asednev** [comment]
Version [1.0.3](https://www.npmjs.com/package/homebridge-plugin-govee/v/1.0.3) adds the support for Raspberry Pi. Update the plugin on you Homebridge and give that a try.
