### ISSUE TITLE
Characteristic was supplied illegal value: number 290 exceeded maximum of 100

### ISSUE THREAD

**Issue by asednev** [asednev/homebridge-plugin-govee#33]
BTW I am testing this on HOOBS 4 Beta now... seems to be working... just getting this in logs...

4/3/2021, 2:58:21 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH50755A3F@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:21 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH5075C68A@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:21 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH5075C68A@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:21 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH5075C68A@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:23 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH50755A3F@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:23 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH50755A3F@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:23 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH50755A3F@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:25 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH5075C68A@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:25 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH5075C68A@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:25 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH5075C68A@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:33 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge E6D8@GVH5075C68A@@Current Relative Humidity] characteristic was supplied illegal value: number 290 exceeded maximum of 100
4/3/2021, 2:58:33 PM
Plugin Govee Bridge
WARNIN

_Originally posted by @saiajin in https://github.com/asednev/homebridge-plugin-govee/issues/30#issuecomment-812931375_

**Comment by saiajin** [comment]
Some new output in the logs:

(node:636) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scanStart listeners added to [Noble]. Use emitter.setMaxListeners() to increase limit
4/13/2021, 6:40:23 PM
Plugin Govee Bridge
ERROR
(node:636) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scanStart listeners added to [Noble]. Use emitter.setMaxListeners() to increase limit
4/13/2021, 6:40:30 PM
Plugin Govee Bridge
ERROR
(node:636) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scanStart listeners added to [Noble]. Use emitter.setMaxListeners() to increase limit
4/13/2021, 6:40:33 PM
Plugin Govee Bridge
ERROR
(node:636) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scanStart listeners added to [Noble]. Use emitter.setMaxListeners() to increase limit
4/13/2021, 6:40:38 PM
Plugin Govee Bridge
ERROR
(node:636) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scanStart listeners added to [Noble]. Use emitter.setMaxListeners() to increase limit
4/13/2021, 6:40:38 PM
Plugin Govee Bridge
ERROR
(node:636) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scanStart listeners added to [Noble]. Use emitter.setMaxListeners() to increase limit
4/13/2021, 6:40:38 PM
Plugin Govee Bridge
ERROR
(node:636) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scanStart listeners added to [Noble]. Use emitter.setMaxListeners() to increase limit
4

**Comment by saiajin** [comment]
I isolated this output in the logs as well:

Plugin Govee Bridge starting
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Loaded plugin 'homebridge-plugin-govee'
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Registering platform 'homebridge-plugin-govee.GoveeBridgePlugin'
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Loading 1 platforms...
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Govee
Finished initializing platform: Govee
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Govee
Loading accessory from cache: GVH5101EEBC
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Govee
Loading accessory from cache: GVH51016D15
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Govee
Loading accessory from cache: GVH510277B8
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Govee
Loading accessory from cache: GVH5075C68A
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Govee
Loading accessory from cache: GVH50755A3F
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Preparing Advertiser for 'Plugin Govee Bridge 7CB2' using bonjour-hap backend!
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Starting to advertise 'Plugin Govee Bridge 7CB2' using bonjour-hap backend!
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Bridge is running on port 59826.
4/13/2021, 6:44:28 PM
Plugin Govee Bridge
Govee
Govee Scan Started
4/13/2021, 6:44:29 PM
Plugin Govee Bridge
Govee
Restoring existing accessory from cache: GVH51016D15
4/13/2021, 6:44:31 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:31 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:31 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:31 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:31 PM
Plugin Govee Bridge
Govee
Restoring existing accessory from cache: GVH50755A3F
4/13/2021, 6:44:32 PM
Plugin Govee Bridge
Govee
Restoring existing accessory from cache: GVH5075C68A
4/13/2021, 6:44:33 PM
Plugin Govee Bridge
Govee
Restoring existing accessory from cache: GVH510277B8
4/13/2021, 6:44:34 PM
Plugin Govee Bridge
Govee
Restoring existing accessory from cache: GVH5101EEBC
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
Govee
Govee Scan Started
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
Govee
Govee Scan Started
4/13/2021, 6:44:36 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge 7CB2@GVH510277B8@@Current Relative Humidity] characteristic was supplied illegal value: number 410 exceeded maximum of 100
4/13/2021, 6:44:37 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge 7CB2@GVH510277B8@@Current Relative Humidity] characteristic was supplied illegal value: number 410 exceeded maximum of 100
4/13/2021, 6:44:37 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge 7CB2@GVH510277B8@@Current Relative Humidity] characteristic was supplied illegal value: number 410 exceeded maximum of 100
4/13/2021, 6:44:38 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:38 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:38 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:38 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:38 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:38 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:38 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:38 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
Govee Scan Started
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
Restart Discovery
4/13/2021, 6:44:43 PM
Plugin Govee Bridge
Govee
Govee Scan Started
4/13/2021, 6:44:45 PM
Plugin Govee Bridge
WARNING
[Plugin Govee Bridge 7CB2@GVH510277B8@@Current Relative Humidity] characteristic was supplied illegal value: number 410 exceeded maximum of 100
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/13/2021, 6:44:46 PM
Plugin Govee Bridge
Govee
Govee Scan Stopped

**Comment by asednev** [comment]
@saiajin I see that https://github.com/hoobs-org/hoobsd/issues/38 was fixed recently. Is this still an issue for you or should I close this issue report?

**Comment by saiajin** [comment]
HI, Now the plugin just crashes... not sure if its the same issue...I have new output from logs and  I cloned https://github.com/asednev/govee-bt-client and ran:

$ cd govee-bt-client
$ npm install
$ npm run dev


The results are in https://github.com/asednev/homebridge-plugin-govee/issues/34

**Comment by asednev** [comment]
None of the humidity values provided in https://github.com/asednev/homebridge-plugin-govee/issues/34#issuecomment-822042509 exceed 100. Can't reproduce the issue without additional logs.
