### ISSUE TITLE
Will this conflict with other plugins?

### ISSUE THREAD

**Issue by Jacksonbm1** [asednev/homebridge-plugin-govee#35]
**Describe Your Problem:**

I had some issues in the past with Bluetooth plugins conflicting. https://github.com/renssies/homebridge-am43-blinds/issues/31

I think one of them was making continuous calls and so was overusing noble while the other couldn't. Have you experienced this/tried this plugin with other plugins using noble? Just wanted to check before buying. 

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by asednev** [comment]
@Jacksonbm1 Personally, I haven't used this plugin along with any other plugins using noble so I can't share my first-hand observations. Nonetheless, this comment is logical and _likely_ true: https://github.com/renssies/homebridge-am43-blinds/issues/31#issuecomment-850841372
