### ISSUE TITLE
Support for more devices possible?

### ISSUE THREAD

**Issue by jeanofthedead** [asednev/homebridge-plugin-govee#4]
I am wondering if it is possible to add similar BT-enabled Govee thermometer/hygrometers? The model I own is [this one](https://www.amazon.com/Bluetooth-Temperature-Thermometer-Hygrometer-Calibration/dp/B07DWMJKP5/). Would love to hear your thoughts - thanks!

**Comment by asednev** [comment]
@jeanofthedead Looks like the model for that one is H5072. I did some research and payloads supposed to be nearly identical to H5075 (model that this plugin was tested with).

Two question:
1. Have you tried to install this plugin as is, does it detect your device?
2. Can you clone https://github.com/asednev/govee-bt-client, run `npm ci` followed by `npm run dev` and provide console output here.

**Comment by jeanofthedead** [comment]
I'm a bit new to all of this. In my log, it's showing this error:

- The requested platform "GoveeHomebridgePlugin" was not registered by any plugin.
- Your config.json is requesting the platform "GoveeHomebridgePlugin" which has not been published by any installed plugins.

Perhaps my config is wrong:

{
            "platform": "GoveeHomebridgePlugin",
            "plugin_map": {
                "plugin_name": "homebridge-plugin-govee"
            },
            "name": "homebridge-plugin-govee",
            "batteryThreshold": "25",
            "debug": true
        }

Btw, I'm using HOOBS instead of HomeBridge, if that helps.

**Comment by asednev** [comment]
The errors that you provided suggest some issues with installing this plugin on HOOBS. Here's what config section for Homebridge looks like:

```
{
    "name": "Govee",
    "batteryThreshold": 25,
    "debug": true,
    "platform": "GoveeHomebridgePlugin"
}
```

you can see how this section is inserted into homebridge config here: https://gist.github.com/asednev/a00f53798b8d8ce604b632cdbdf953cd

You may want to verify that plugin is actually installed and the config is correct. Unfortunately, I can't provide you any help with HOOBS.

If you manage to get past those errors and your device isn't detected by the plugin, send me logs that you're getting and I'll try to help with the next steps.

**Comment by joshspicer** [comment]
I can confirm the `H5072` works great with this plugin
