### ISSUE TITLE
H5074 stops updating after several hours

### ISSUE THREAD

**Issue by idsnowghost** [asednev/homebridge-plugin-govee#40]
Only using one Govee sensor (H5074) with the plugin and it seems to stop updating several hours after Homebridge starts:

Here's the debug log while working:

discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -63
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740d6dc2]
discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -70
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740d6dc2]
discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -60
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740d6dc2]
discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -62
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740d6dc2]
discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -62
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f485750740d6dc2]
discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -63
e38c81326d0d: 88ec0078038c136402
discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -71
e38c81326d0d: 88ec0078038c136402

Debug log once it stops updating:

discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -50
e38c81326d0d: 88ec0058045b0e6402
discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -65
e38c81326d0d: 88ec0058045b0e6402
discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -50
e38c81326d0d: 88ec0058045b0e6402
discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -66
e38c81326d0d: 88ec0058045b0e6402
discovered e38c81326d0d e38c81326d0d e3:8c:81:32:6d:0d disconnected -50
e38c81326d0d: 88ec0058045b0e6402

**Comment by myatyia** [comment]
I have been having the same exact issue for a while with H5075. If someone knows what's going on that'd be really helpful.

**Comment by asednev** [comment]
This looks like another instance of https://github.com/asednev/homebridge-plugin-govee/issues/19. Closing.
