### ISSUE TITLE
Remove Device from Homekit

### ISSUE THREAD

**Issue by MrFly72** [asednev/homebridge-plugin-govee#42]
**Describe Your Problem:**
I am seeing 3 devices with different names instead of 2. My believe is, that one of my neighbors has on of the H5075, which will show in my Govee Pluign.

**Logs:**
[12/11/2021, 10:56:51] [Govee] Adding new accessory: GVH50753B9C
[12/11/2021, 10:56:54] [Govee] Adding new accessory: GVH507552D0
[12/11/2021, 10:57:06] [Govee] Adding new accessory: GVH50759447

the one with 2D0 is not mine.

I tried to disable it on the Homebridge GUI by hiding it, but it will end up in homekit anyhow and cannot delete it in homekit.
Is there any way to configure the Govee Plugin to not deliver this device anymore.
And if not, I believe it would be a needed enhancement.

**Comment by MrFly72** [comment]
I was able to produce a temporary solution for myself to ignore the device:
![image](https://user-images.githubusercontent.com/65505278/142932272-3cb79d3b-df1f-4ab8-9ed4-2176b57c728d.jpeg)

**Comment by asednev** [comment]
@MrFly72 that's fantastic. Homebridge supports configurations for plugins which can be used to maintain the list of ignored devices outside of code: https://developers.homebridge.io/#/config-schema

**Comment by MrFly72** [comment]
Ok, i know have it quite nice setup, I believe. As said, I am not a great Java developer.....
Added this to the config:
      "IgnoreDeviceNames": {
         "title": "Ignored DeviceNames",
         "type": "array",
           "items": {
          "title": "DeviceName",
          "type": "string"
        }
      }
 and this to the code:
        const displayName = `${this.sanitize(reading.model)}`;
        //this.log.info("Current List of Ignored Devices: ",this.config.IgnoreDeviceNames);
        const IgnoredDeviceNames = this.config.IgnoreDeviceNames;
        if( IgnoredDeviceNames.includes(displayName)) { // it will return true if you `foo` is one of array values else false
           this.log.debug("Device in Ignore List", displayName," skipping the device!");
           return;
        }
This is the config dialog:
![2021-11-23 10_07_24-Homebridge](https://user-images.githubusercontent.com/65505278/142997154-3054de5a-6423-415c-963d-a8d9b062bf69.png)

**Comment by asednev** [comment]
Thanks for your contribution in PR https://github.com/asednev/homebridge-plugin-govee/pull/48. This has been published in version 1.1.4

**Comment by sdiegel** [comment]
I'm having this issue on v1.1.6. I have five devices that don't match any of my devices' serial numbers. I added each value to the Ignored DeviceNames list one at a time, and restarted Homebridge and the Home app and they aren't going away. Any advice?

**Comment by MrFly72** [comment]
ONCE found they don't disappear. You have to delete them through homebridge as they are cached.

**Comment by sdiegel** [comment]
> ONCE found they don't disappear. You have to delete them through homebridge as they are cached.

Thanks for the quick response! I wasn't aware of this functionality. It worked perfectly.

**Comment by MrFly72** [comment]
I only have 2 devices I have to ignore and 4 to be mine ;-)
Maybe you are my neighbor and see my 4 + the one in my campingcar 😂😂😂
