### ISSUE TITLE
Govee plugin no longer works after the upgrade to node 16.13

### ISSUE THREAD

**Issue by 1ne** [asednev/homebridge-plugin-govee#44]
**Describe The Bug:**
After the upgrade to Node 16.13 the govee Homebridge plugin no longer loads. 

**To Reproduce:**
Upgrading to Node 16.13 and rebooting the service causes this. The downgrade back to Node 14 makes the plugin work again. 

**Expected behavior:**
The plugin should work the sameway regardless of the node version.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
        {
            "name": "Govee",
            "batteryThreshold": 20,
            "debug": false,
            "humidityOffset": 0,
            "platform": "GoveeHomebridgePlugin",
            "_bridge": {
                "username": "0E:AA:3C:XX:XX:XX",
                "port": 57030
            }
        },
```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-plugin-govee v1.1.2
* **Homebridge Version**: 1.3.6
* **Node.js Version**: 16.13.0
* **NPM Version**: 8.1.2
* **Operating System**: Raspbian

**Comment by PixelBurstHD** [comment]
Can confirm - same everything else but Ubuntu OS.

**Comment by aidupre** [comment]
Confirm this is happening to me as well

**Comment by roundaboutluke** [comment]
Is anyone able to get any log output? Mine doesn’t show anything, it’s like it doesn’t even start, setting Homebridge and the plugin to debug and there isn’t even an entry in my logs. 

It also doesn’t show in the child bridge list despite being set as one.

Going to the plugins page I can see it’s a child bridge and issue a restart, but still no output.

**Comment by roundaboutluke** [comment]
Fully removed plugin and config, restarted homebridge then readded plugin and reconfigured now working fine. YMMV 👍

**Comment by fwbochum** [comment]
> Fully removed plugin and config, restarted homebridge then readded plugin and reconfigured now working fine. YMMV 👍

Works for me, too. Thanks for the advice.

**Comment by roundaboutluke** [comment]
@1ne give this a try

**Comment by 1ne** [comment]
Thanks for your suggestion @roundaboutluke this fixed it. Closing out this issue. 

Now I am seeing way too many "ghost" devices that are non-existent I believe its un-related.
