### ISSUE TITLE
Values are not updated and too many tiles

### ISSUE THREAD

**Issue by ARPIpappen** [asednev/homebridge-plugin-govee#51]
I use the plugin in my homebridge with v16.13.1. The plugin is up to date.
I am currently using two govee sensors.
1. Bug: The values are not currently synchronized. This means that the sensor delivers a different value than the home app.
2. Bug: e are now shown ten tiles instead of four in the home app, how can I delete that?

I look forward to an answer.
![IMG_0118](https://user-images.githubusercontent.com/96337334/146639222-1bd52df9-3d6e-4b9a-9413-3953f4f9eca1.jpg)

LG

**Comment by asednev** [comment]
@ARPIpappen Your system might be picking up readings from other Govee devices, perhaps your neighbors. 

You can use `Remove Single Cached Accessory` in Homebridge to delete unwanted accessories but they will reappear. If you want to permanently ignore, you can try v1.1.4 which has a new feature: https://github.com/asednev/homebridge-plugin-govee/issues/42
