### ISSUE TITLE
Update to 1.25 from 1.1.4 fails due to 404

### ISSUE THREAD

**Issue by smazo** [asednev/homebridge-plugin-govee#73]
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/bluetooth_hci_socket-0.5.3-8-node-v93-linux-arm.tar.gz

**Comment by asednev** [comment]
@smazo [node-bluetooth-hci-socket](https://github.com/abandonware/node-bluetooth-hci-socket) is most likely a dependency of [noble](https://github.com/abandonware/noble) which hasn't changed the version between v1.1.4 and v1.2.5.

Try cleaning node cache and see if that helps:
`$ npm cache clean –force`

If you still have this issue, tell me more about your setup. What is you OS and node versions?
