### ISSUE TITLE
Holy rounding, batman!

### ISSUE THREAD

**Issue by clogan2** [asednev/homebridge-plugin-govee#9]
From what I can tell, it looks like temperature is ROUNDED UP, to the nearest degree. Why?

Why not, not round at all and just give the temperature to the tens?

**Comment by asednev** [comment]
This plug exposes raw value from the temperature sensor to Homekit. You can find the raw value by opening settings for your accessory on Homebridge Accessories page. It seems that Home app rounds up (or down) the value before displaying to the end user.

<img width="694" alt="Untitled2" src="https://user-images.githubusercontent.com/3236025/103104087-2ae88280-45da-11eb-9e14-f3c4520a189b.png">


<img width="1121" alt="Untitled" src="https://user-images.githubusercontent.com/3236025/103103966-7cdcd880-45d9-11eb-9c55-2ad257f93010.png">

If you find a way to turn off rounding in Home app, please share!
